server {
    listen       8080;
    server_name  _;
    root         /usr/share/nginx/html;
    index        index.html;

    gzip on;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml application/xml;

    # Assets com hash: cache agressivo.
    location ~* \.(?:js|css|png|jpg|jpeg|gif|ico|svg|woff2?|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # index.html nunca em cache (garante que novos deploys apareçam).
    location = /index.html {
        add_header Cache-Control "no-cache";
    }

    # Fallback SPA: qualquer rota cai no index.html (Angular router).
    location / {
        try_files $uri $uri/ /index.html;
    }
}
